"""evidence-store: an S3 evidence store in a GitHub repository.

  evidence-store init    --repo OWNER/NAME --root ROOT [--pages-workflow FILE] [--claim NAME]
  evidence-store intake  --repo OWNER/NAME --outcome FILE [--event PATH --event-name NAME] [--sweep-days N]
  evidence-store apply   --repo OWNER/NAME --outcome FILE
  evidence-store check   [--base REV] [--author LOGIN]
  evidence-store submit  --repo OWNER/NAME --decl NAME --verdict accept|problem|question --agent "TOOL, MODEL" …
  evidence-store challenge --repo OWNER/NAME --decl NAME --property TEXT [--statement LEAN] …
  evidence-store test    --repo OWNER/NAME --decl NAME --test NAME [--checks TEXT]
  evidence-store name    --repo OWNER/NAME --decl NAME --name TEXT [--what result|definition] …
  evidence-store comment --repo OWNER/NAME --issue N --text TEXT [--agent "TOOL, MODEL"]
  evidence-store status  --repo OWNER/NAME --record ID --action withdraw|fixed|met|… [--test NAME] [--note T]

`init` sets a repository up: the store's directory, the issue forms, and the workflows that run
intake and check changes. `intake` and `apply` are what the intake workflow runs. `submit` and
`comment` are how an AI agent (or anyone at a terminal) writes what the forms would.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

from evidence_core import records as rec
from evidence_core import rubric as rb
from evidence_core import store as sto

from . import forms
from .intake import Context, Outcome, process

ACTIONS_REF = "main"

INTAKE_WORKFLOW = """\
# Generated by evidence-store (`evidence-store init`).
# Turns issues opened with the evidence forms, and the comments on them, into S3 records in the
# store, and says so on the issue. A sweep every six hours catches what a dropped run missed.
name: Evidence intake

on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created]
  schedule:
    - cron: '23 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  actions: write

concurrency:
  group: evidence-intake
  cancel-in-progress: false

jobs:
  intake:
    # Not the bot's own closes and labels: a close by hand is a status, the bot's follows one. (Comments by
    # bots are read: an agent can act through a bot account.)
    if: ${{{{ !github.event.issue.pull_request && !(github.event_name == 'issues' && github.event.sender.type == 'Bot') }}}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: LeanTrustBuilders/evidence-store/intake@{ref}
        with:
          store: {store}
          pages-workflow: '{pages}'
"""

CHECK_WORKFLOW = """\
# Generated by evidence-store (`evidence-store init`).
# Checks every change to the evidence store: records valid, none changed or removed, and those a pull
# request adds written by its author.
name: Evidence check

on:
  pull_request:
    paths: ['{store}/**']
  push:
    branches: [main]
    paths: ['{store}/**']

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: LeanTrustBuilders/evidence-store/check@{ref}
        with:
          store: {store}
"""


def cmd_init(args) -> int:
    root = Path(args.dir)
    store_dir = root / args.store
    if (store_dir / sto.CONFIG).exists():
        store = sto.Store.load(store_dir)
        print(f"{store_dir}: already a store ({len(store.records)} records); updating forms and workflows")
    else:
        config = sto.default_config(args.repo, args.root, args.datasets_repo or None)
        config["claims"] = args.claim
        store = sto.Store.init(store_dir, config)
        print(f"{store_dir}: new store for {args.repo}")
    write_forms(root, store.rubric)
    wf = root / ".github" / "workflows"
    wf.mkdir(parents=True, exist_ok=True)
    (wf / "evidence-intake.yml").write_text(INTAKE_WORKFLOW.format(ref=ACTIONS_REF, store=args.store,
                                                                   pages=args.pages_workflow))
    (wf / "evidence-check.yml").write_text(CHECK_WORKFLOW.format(ref=ACTIONS_REF, store=args.store))
    print("wrote .github/ISSUE_TEMPLATE/evidence-*.yml and .github/workflows/evidence-{intake,check}.yml")
    if args.labels:
        from .github import ensure_labels
        ensure_labels(args.repo)
        print("created the labels")
    return 0


def write_forms(root: Path, rubric: rb.Rubric) -> None:
    d = root / ".github" / "ISSUE_TEMPLATE"
    d.mkdir(parents=True, exist_ok=True)
    for kind, f in forms.forms(rubric).items():
        (d / f["file"]).write_text(forms.template(kind, rubric), encoding="utf-8")


def cmd_intake(args) -> int:
    from . import github
    store = sto.Store.load(args.store)
    ctx = Context(repo=args.repo, store=store,
                  dataset=github.Datasets(store.config, override=Path(args.dataset) if args.dataset else None),
                  maintainers=frozenset(store.config.get("maintainers", [])))
    todo: list[tuple[int, bool]] = []
    if args.event and args.event_name in ("issues", "issue_comment"):
        event = json.loads(Path(args.event).read_text())
        todo.append((event["issue"]["number"], True))
    if args.sweep_days:
        since = (datetime.now(timezone.utc) - timedelta(days=args.sweep_days)).strftime("%Y-%m-%dT%H:%M:%SZ")
        todo += [(i["number"], False) for i in github.recent_issues(args.repo, since)]
    out, done = Outcome(), set()
    for number, announce in todo:
        if number in done:
            continue
        done.add(number)
        issue = github.issue(args.repo, number)
        cs = github.comments(args.repo, number) if issue.get("comments") else []
        # Closes and reopens by hand are statuses; an issue never closed has none to read.
        evs = github.events(args.repo, number) if issue.get("closed_at") else []
        out.merge(process(issue, cs, ctx, announce=announce, events=evs))
    Path(args.outcome).write_text(json.dumps(out.as_json(), indent=1))
    print(f"intake: {len(done)} issues read, {len(out.records)} records added")
    return 0


def cmd_apply(args) -> int:
    from . import github
    github.apply(json.loads(Path(args.outcome).read_text()), args.repo)
    return 0


def cmd_check(args) -> int:
    store = sto.Store.load(Path(args.repo_dir) / args.store)
    after = store.records
    before = sto.records_at(args.repo_dir, args.base, args.store) if args.base else []
    errs = sto.check(before, after, author=args.author or None, rubrics={store.rubric.name: store.rubric})
    for e in errs:
        print(f"::error::{e}")
    new = len({r["id"] for r in after} - {r["id"] for r in before})
    print(f"{len(after)} records, {new} new" + (f" since {args.base}" if args.base else "") +
          (f", {len(errs)} problems" if errs else ", ok"))
    return 1 if errs else 0


def cmd_add(args) -> int:
    """Adds the records of a file (a reader's export, say) to a store, as a pull request would: each
    checked and given its id; records the store has are skipped."""
    store = sto.Store.load(args.store)
    records = rec.load(args.file)
    try:
        added = store.add(records)
    except sto.StoreError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    print(f"{len(added)} records added to {args.store}, {len(records) - len(added)} already there")
    return 0


def cmd_dataset(args) -> int:
    """Fetches datasets published as releases: where a store's config says (``store.json``,
    ``datasets``), or where ``--repo``/``--tag`` say for a repository without a store."""
    from .github import Datasets
    config = {"repo": None, "tag": "dataset-{commit12}", "asset": "dataset.tar.gz"}
    store_dir = Path(args.store)
    if (store_dir / sto.CONFIG).exists():
        config.update(sto.Store.load(store_dir).config["datasets"])
    for key in ("repo", "tag", "asset"):
        if getattr(args, key):
            config[key] = getattr(args, key)
    if not config["repo"]:
        print(f"no store at {store_dir}: say where the datasets are with --repo (and --tag)", file=sys.stderr)
        return 2
    ds = Datasets({"datasets": config}, cache=Path(args.out))
    out = Path(args.out)
    try:
        if args.all:
            for tag in ds.tags():
                print(ds.download(tag, out / tag))
        else:
            tag = ds.tag(args.commit or "")
            print(ds.download(tag, out))
    except (LookupError, RuntimeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    return 0


def agent_mark(agent: str) -> str:
    a = rec.parse_agent(agent)
    return "<!-- agent: " + "; ".join(f"{k}={v}" for k, v in a.items()) + " -->"


def store_rubric(repo: str) -> rb.Rubric:
    """The rubric of the store in a repository, from its ``store.json`` on GitHub."""
    from . import github
    return rb.of_config(github.store_config(repo))


def axes(given: str, rubric: rb.Rubric, other: bool = False) -> list[str]:
    """Comma-separated axis names, each one of ``rubric``'s (or ``other``, if allowed)."""
    names = [n.strip() for n in given.split(",") if n.strip()]
    allowed = rubric.names + ([rb.OTHER] if other else [])
    unknown = [n for n in names if n not in allowed]
    if unknown:
        raise SystemExit(f"error: {', '.join(unknown)}: not an axis of {rubric.name} "
                         f"({', '.join(allowed)})")
    return names


def cmd_submit(args) -> int:
    kind = {"accept": "review", "problem": "problem", "question": "question"}[args.verdict]
    rubric = store_rubric(args.repo)
    answers = {"decl": args.decl, "commit": args.commit, "involvement": args.involvement,
               "who": "agent" if args.agent else "person", "agent": args.agent}
    if kind == "review":
        checked = axes(args.checked, rubric)
        axes(",".join(c.split(":", 1)[0] for c in args.caveat if ":" in c), rubric, other=True)
        answers.update(reference=args.reference, rationale=args.rationale,
                       caveats="\n".join(args.caveat),
                       checked={n: n in checked for n in rubric.names} if checked else {})
    elif kind == "problem":
        category = axes(args.category, rubric, other=True)
        if len(category) > 1:
            raise SystemExit("error: --category takes one axis")
        answers.update(category=category[0] if category else rb.OTHER, rationale=args.rationale)
    else:
        answers.update(question=args.question or args.rationale)
    text = forms.body(kind, answers, rubric)
    title = forms.FORMS[kind]["title"] + args.decl
    if args.dry_run:
        print(f"{title}\n\n{text}")
        return 0
    from . import github
    print(github.create_issue(args.repo, title, text, forms.FORMS[kind]["label"]))
    return 0


def open_form(args, kind: str, answers: dict, rubric: rb.Rubric = rb.STANDARD) -> int:
    answers = {"decl": args.decl, "commit": args.commit, "who": "agent" if args.agent else "person",
               "agent": args.agent, **answers}
    text = forms.body(kind, answers, rubric)
    title = forms.FORMS[kind]["title"] + args.decl
    if args.dry_run:
        print(f"{title}\n\n{text}")
        return 0
    from . import github
    print(github.create_issue(args.repo, title, text, forms.FORMS[kind]["label"]))
    return 0


def cmd_challenge(args) -> int:
    rubric = store_rubric(args.repo)
    modes = axes(args.modes, rubric)
    return open_form(args, "challenge", {"property": args.property, "statement": args.statement,
                                         "catches": args.catches, "involvement": args.involvement,
                                         "modes": {n: n in modes for n in rubric.names} if modes else {}},
                     rubric)


def cmd_test(args) -> int:
    return open_form(args, "test", {"test": args.test, "checks": args.checks,
                                    "involvement": args.involvement})


def cmd_name(args) -> int:
    return open_form(args, "named", {"name": args.name, "what": args.what, "about": args.about,
                                     "source": args.source})


def cmd_status(args) -> int:
    answers = {"record": args.record, "action": args.action, "commit": args.commit, "note": args.note,
               "test": args.test, "who": "agent" if args.agent else "person", "agent": args.agent}
    text = forms.body("status", answers)
    title = f"Status: {args.action} {args.record}"
    if args.dry_run:
        print(f"{title}\n\n{text}")
        return 0
    from . import github
    print(github.create_issue(args.repo, title, text, forms.FORMS["status"]["label"]))
    return 0


def cmd_comment(args) -> int:
    text = args.text + (f"\n\n{agent_mark(args.agent)}" if args.agent else "")
    if args.dry_run:
        print(text)
        return 0
    from . import github
    print(github.comment(args.repo, args.issue, text))
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="evidence-store", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    q = sub.add_parser("init", help="set a repository up with an evidence store")
    q.add_argument("--repo", required=True, help="the repository, owner/name")
    q.add_argument("--root", required=True, help="the library's root module")
    q.add_argument("--dir", default=".", help="the repository's checkout")
    q.add_argument("--store", default="evidence")
    q.add_argument("--datasets-repo", help="where the dataset releases are (default: --repo)")
    q.add_argument("--pages-workflow", default="", help="a workflow to run when records are added")
    q.add_argument("--claim", action="append", default=[], help="a claim the store is about")
    q.add_argument("--labels", action="store_true", help="also create the labels (needs gh)")
    q.set_defaults(fn=cmd_init)

    q = sub.add_parser("intake", help="records from issues and comments")
    q.add_argument("--repo", required=True)
    q.add_argument("--store", default="evidence")
    q.add_argument("--event", help="the event payload ($GITHUB_EVENT_PATH)")
    q.add_argument("--event-name", default="", help="$GITHUB_EVENT_NAME")
    q.add_argument("--sweep-days", type=int, default=0, help="also read the issues updated in these days")
    q.add_argument("--dataset", help="use this dataset for every commit (for tests)")
    q.add_argument("--outcome", required=True, help="where to write what to do on GitHub")
    q.set_defaults(fn=cmd_intake)

    q = sub.add_parser("apply", help="reply, label and close as intake decided")
    q.add_argument("--repo", required=True)
    q.add_argument("--outcome", required=True)
    q.set_defaults(fn=cmd_apply)

    q = sub.add_parser("add", help="add the records of a file to the store (for a pull request)")
    q.add_argument("file", help="records, one JSON object per line (ids are set here)")
    q.add_argument("--store", default="evidence")
    q.set_defaults(fn=cmd_add)

    q = sub.add_parser("dataset", help="fetch the dataset of a commit (or every one) from its release")
    q.add_argument("--store", default="evidence", help="the store whose config says where datasets are")
    q.add_argument("--commit", help="the library commit (default: the latest dataset)")
    q.add_argument("--all", action="store_true", help="every dataset, each into OUT/<tag>, oldest first")
    q.add_argument("--repo", help="the repository whose releases hold the datasets (default: the store's)")
    q.add_argument("--tag", help="the release tag, with {commit12} or {commit} (default: the store's)")
    q.add_argument("--asset", help="the release asset (default: dataset.tar.gz)")
    q.add_argument("--out", required=True, help="where to unpack it (with --all, a directory of them)")
    q.set_defaults(fn=cmd_dataset)

    q = sub.add_parser("check", help="check a change to the store")
    q.add_argument("--repo-dir", default=".")
    q.add_argument("--store", default="evidence")
    q.add_argument("--base", help="the revision before the change")
    q.add_argument("--author", help="new records must be by this GitHub login")
    q.set_defaults(fn=cmd_check)

    q = sub.add_parser("submit", help="open a review, problem or question, as the forms do")
    q.add_argument("--repo", required=True)
    q.add_argument("--decl", required=True)
    q.add_argument("--verdict", required=True, choices=["accept", "problem", "question"])
    q.add_argument("--commit", default="")
    q.add_argument("--reference", default="")
    q.add_argument("--checked", default="", help="comma-separated axes of the store's rubric (ltb-rubric/1: "
                   "object,convention,edge-cases,junk,vacuous,choice,generality,naming)")
    q.add_argument("--caveat", action="append", default=[], help="'AXIS: note' (repeatable)")
    q.add_argument("--rationale", default="")
    q.add_argument("--category", default="other", help="for a problem: an axis of the store's rubric, or other")
    q.add_argument("--question", default="")
    q.add_argument("--involvement", default="outsider", choices=["outsider", "contributor", "author"])
    q.add_argument("--agent", default="", help="'TOOL, MODEL[, session S]': an AI agent wrote it")
    q.add_argument("--dry-run", action="store_true", help="print the issue instead of opening it")
    q.set_defaults(fn=cmd_submit)

    def common(q, decl=True):
        q.add_argument("--repo", required=True)
        if decl:
            q.add_argument("--decl", required=True)
            q.add_argument("--commit", default="")
        q.add_argument("--agent", default="", help="'TOOL, MODEL[, session S]': an AI agent wrote it")
        q.add_argument("--dry-run", action="store_true", help="print the issue instead of opening it")

    q = sub.add_parser("challenge", help="propose a test of a declaration, as the challenge form does")
    common(q)
    q.add_argument("--property", required=True, help="what it should satisfy")
    q.add_argument("--statement", default="", help="the property as a Lean statement")
    q.add_argument("--catches", default="", help="what a wrong definition would get wrong here")
    q.add_argument("--modes", default="", help="comma-separated axes of the store's rubric it would catch "
                   "a problem on")
    q.add_argument("--involvement", default="outsider", choices=["outsider", "contributor", "author"])
    q.set_defaults(fn=cmd_challenge)

    q = sub.add_parser("test", help="list a declaration of the library that tests another")
    common(q)
    q.add_argument("--test", required=True, help="the full name of the testing declaration")
    q.add_argument("--checks", default="", help="what it checks (required for agents)")
    q.add_argument("--involvement", default="outsider", choices=["outsider", "contributor", "author"])
    q.set_defaults(fn=cmd_test)

    q = sub.add_parser("name", help="name a result or notable definition")
    common(q)
    q.add_argument("--name", required=True)
    q.add_argument("--what", default="result", choices=["result", "definition"])
    q.add_argument("--about", default="")
    q.add_argument("--source", default="")
    q.set_defaults(fn=cmd_name)

    q = sub.add_parser("status", help="change a record's state, as the status form does")
    q.add_argument("--repo", required=True)
    q.add_argument("--record", required=True, help="the id of the record")
    q.add_argument("--action", required=True, choices=["withdraw", "fixed", "intended", "invalid", "answered",
                                                       "met", "failed", "declined", "reopen"])
    q.add_argument("--test", default="", help="for met: the declaration that meets the challenge")
    q.add_argument("--commit", default="", help="for fixed: the commit that fixed it")
    q.add_argument("--note", default="")
    q.add_argument("--agent", default="", help="'TOOL, MODEL[, session S]': an AI agent asks for it")
    q.add_argument("--dry-run", action="store_true")
    q.set_defaults(fn=cmd_status)

    q = sub.add_parser("comment", help="comment on a review, problem or question")
    q.add_argument("--repo", required=True)
    q.add_argument("--issue", required=True, type=int)
    q.add_argument("--text", required=True, help="a reply, or a command: /fixed COMMIT, /answered, …")
    q.add_argument("--agent", default="", help="'TOOL, MODEL[, session S]': an AI agent wrote it")
    q.add_argument("--dry-run", action="store_true")
    q.set_defaults(fn=cmd_comment)

    args = p.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
