"""evidence-store: an S3 evidence store in a GitHub repository.

  evidence-store init    --repo OWNER/NAME --root ROOT [--pages-workflow FILE] [--claim NAME]
  evidence-store intake  --repo OWNER/NAME --outcome FILE [--event PATH --event-name NAME] [--sweep-days N]
  evidence-store apply   --repo OWNER/NAME --outcome FILE
  evidence-store check   [--base REV] [--author LOGIN]
  evidence-store submit  --repo OWNER/NAME --decl NAME --verdict accept|problem|question --agent "TOOL, MODEL" …
  evidence-store comment --repo OWNER/NAME --issue N --text TEXT [--agent "TOOL, MODEL"]

`init` sets a repository up: the store's directory, the issue forms, and the workflows that run
intake and check changes. `intake` and `apply` are what the intake workflow runs. `submit` and
`comment` are how an AI agent (or anyone at a terminal) writes what the forms would.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

from evidence_core import records as rec
from evidence_core import store as sto

from . import forms
from .intake import Context, Outcome, process

ACTIONS_REF = "main"

INTAKE_WORKFLOW = """\
# Generated by evidence-store (`evidence-store init`).
# Turns issues opened with the evidence forms, and the comments on them, into S3 records in the
# store, and says so on the issue. A sweep every six hours catches what a dropped run missed.
name: Evidence intake

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]
  schedule:
    - cron: '23 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  actions: write

concurrency:
  group: evidence-intake
  cancel-in-progress: false

jobs:
  intake:
    if: ${{{{ !github.event.issue.pull_request }}}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: LeanTrustBuilders/evidence-store/intake@{ref}
        with:
          store: {store}
          pages-workflow: '{pages}'
"""

CHECK_WORKFLOW = """\
# Generated by evidence-store (`evidence-store init`).
# Checks every change to the evidence store: records valid, none changed or removed, and those a pull
# request adds written by its author.
name: Evidence check

on:
  pull_request:
    paths: ['{store}/**']
  push:
    branches: [main]
    paths: ['{store}/**']

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: LeanTrustBuilders/evidence-store/check@{ref}
        with:
          store: {store}
"""


def cmd_init(args) -> int:
    root = Path(args.dir)
    store_dir = root / args.store
    if (store_dir / sto.CONFIG).exists():
        store = sto.Store.load(store_dir)
        print(f"{store_dir}: already a store ({len(store.records)} records); updating forms and workflows")
    else:
        config = sto.default_config(args.repo, args.root, args.datasets_repo or None)
        config["claims"] = args.claim
        sto.Store.init(store_dir, config)
        print(f"{store_dir}: new store for {args.repo}")
    write_forms(root)
    wf = root / ".github" / "workflows"
    wf.mkdir(parents=True, exist_ok=True)
    (wf / "evidence-intake.yml").write_text(INTAKE_WORKFLOW.format(ref=ACTIONS_REF, store=args.store,
                                                                   pages=args.pages_workflow))
    (wf / "evidence-check.yml").write_text(CHECK_WORKFLOW.format(ref=ACTIONS_REF, store=args.store))
    print("wrote .github/ISSUE_TEMPLATE/evidence-*.yml and .github/workflows/evidence-{intake,check}.yml")
    if args.labels:
        from .github import ensure_labels
        ensure_labels(args.repo)
        print("created the labels")
    return 0


def write_forms(root: Path) -> None:
    d = root / ".github" / "ISSUE_TEMPLATE"
    d.mkdir(parents=True, exist_ok=True)
    for kind, f in forms.FORMS.items():
        (d / f["file"]).write_text(forms.template(kind), encoding="utf-8")


def cmd_intake(args) -> int:
    from . import github
    store = sto.Store.load(args.store)
    ctx = Context(repo=args.repo, store=store,
                  dataset=github.Datasets(store.config, override=Path(args.dataset) if args.dataset else None),
                  maintainers=frozenset(store.config.get("maintainers", [])))
    todo: list[tuple[int, bool]] = []
    if args.event and args.event_name in ("issues", "issue_comment"):
        event = json.loads(Path(args.event).read_text())
        todo.append((event["issue"]["number"], True))
    if args.sweep_days:
        since = (datetime.now(timezone.utc) - timedelta(days=args.sweep_days)).strftime("%Y-%m-%dT%H:%M:%SZ")
        todo += [(i["number"], False) for i in github.recent_issues(args.repo, since)]
    out, done = Outcome(), set()
    for number, announce in todo:
        if number in done:
            continue
        done.add(number)
        issue = github.issue(args.repo, number)
        cs = github.comments(args.repo, number) if issue.get("comments") else []
        out.merge(process(issue, cs, ctx, announce=announce))
    Path(args.outcome).write_text(json.dumps(out.as_json(), indent=1))
    print(f"intake: {len(done)} issues read, {len(out.records)} records added")
    return 0


def cmd_apply(args) -> int:
    from . import github
    github.apply(json.loads(Path(args.outcome).read_text()), args.repo)
    return 0


def cmd_check(args) -> int:
    after = sto.Store.load(Path(args.repo_dir) / args.store).records
    before = sto.records_at(args.repo_dir, args.base, args.store) if args.base else []
    errs = sto.check(before, after, author=args.author or None)
    for e in errs:
        print(f"::error::{e}")
    new = len({r["id"] for r in after} - {r["id"] for r in before})
    print(f"{len(after)} records, {new} new" + (f" since {args.base}" if args.base else "") +
          (f", {len(errs)} problems" if errs else ", ok"))
    return 1 if errs else 0


def agent_mark(agent: str) -> str:
    a = rec.parse_agent(agent)
    return "<!-- agent: " + "; ".join(f"{k}={v}" for k, v in a.items()) + " -->"


def cmd_submit(args) -> int:
    kind = {"accept": "review", "problem": "problem", "question": "question"}[args.verdict]
    answers = {"decl": args.decl, "commit": args.commit, "involvement": args.involvement,
               "who": "agent" if args.agent else "person", "agent": args.agent}
    if kind == "review":
        answers.update(reference=args.reference, rationale=args.rationale,
                       caveats="\n".join(args.caveat),
                       checked={code: code in args.checked.split(",") for code, _ in forms.CHECKS}
                       if args.checked else {})
    elif kind == "problem":
        answers.update(category=args.category, rationale=args.rationale)
    else:
        answers.update(question=args.question or args.rationale)
    text = forms.body(kind, answers)
    title = forms.FORMS[kind]["title"] + args.decl
    if args.dry_run:
        print(f"{title}\n\n{text}")
        return 0
    from . import github
    print(github.create_issue(args.repo, title, text, forms.FORMS[kind]["label"]))
    return 0


def cmd_comment(args) -> int:
    text = args.text + (f"\n\n{agent_mark(args.agent)}" if args.agent else "")
    if args.dry_run:
        print(text)
        return 0
    from . import github
    print(github.comment(args.repo, args.issue, text))
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="evidence-store", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    q = sub.add_parser("init", help="set a repository up with an evidence store")
    q.add_argument("--repo", required=True, help="the repository, owner/name")
    q.add_argument("--root", required=True, help="the library's root module")
    q.add_argument("--dir", default=".", help="the repository's checkout")
    q.add_argument("--store", default="evidence")
    q.add_argument("--datasets-repo", help="where the dataset releases are (default: --repo)")
    q.add_argument("--pages-workflow", default="", help="a workflow to run when records are added")
    q.add_argument("--claim", action="append", default=[], help="a claim the store is about")
    q.add_argument("--labels", action="store_true", help="also create the labels (needs gh)")
    q.set_defaults(fn=cmd_init)

    q = sub.add_parser("intake", help="records from issues and comments")
    q.add_argument("--repo", required=True)
    q.add_argument("--store", default="evidence")
    q.add_argument("--event", help="the event payload ($GITHUB_EVENT_PATH)")
    q.add_argument("--event-name", default="", help="$GITHUB_EVENT_NAME")
    q.add_argument("--sweep-days", type=int, default=0, help="also read the issues updated in these days")
    q.add_argument("--dataset", help="use this dataset for every commit (for tests)")
    q.add_argument("--outcome", required=True, help="where to write what to do on GitHub")
    q.set_defaults(fn=cmd_intake)

    q = sub.add_parser("apply", help="reply, label and close as intake decided")
    q.add_argument("--repo", required=True)
    q.add_argument("--outcome", required=True)
    q.set_defaults(fn=cmd_apply)

    q = sub.add_parser("check", help="check a change to the store")
    q.add_argument("--repo-dir", default=".")
    q.add_argument("--store", default="evidence")
    q.add_argument("--base", help="the revision before the change")
    q.add_argument("--author", help="new records must be by this GitHub login")
    q.set_defaults(fn=cmd_check)

    q = sub.add_parser("submit", help="open a review, problem or question, as the forms do")
    q.add_argument("--repo", required=True)
    q.add_argument("--decl", required=True)
    q.add_argument("--verdict", required=True, choices=["accept", "problem", "question"])
    q.add_argument("--commit", default="")
    q.add_argument("--reference", default="")
    q.add_argument("--checked", default="", help="comma-separated: F1,F2,F3,F4,F5,F6,F7,F9,naming")
    q.add_argument("--caveat", action="append", default=[], help="'F3: note' (repeatable)")
    q.add_argument("--rationale", default="")
    q.add_argument("--category", default="other", help="for a problem: F1 … F9, naming, other")
    q.add_argument("--question", default="")
    q.add_argument("--involvement", default="outsider", choices=["outsider", "contributor", "author"])
    q.add_argument("--agent", default="", help="'TOOL, MODEL[, session S]': an AI agent wrote it")
    q.add_argument("--dry-run", action="store_true", help="print the issue instead of opening it")
    q.set_defaults(fn=cmd_submit)

    q = sub.add_parser("comment", help="comment on a review, problem or question")
    q.add_argument("--repo", required=True)
    q.add_argument("--issue", required=True, type=int)
    q.add_argument("--text", required=True, help="a reply, or a command: /fixed COMMIT, /answered, …")
    q.add_argument("--agent", default="", help="'TOOL, MODEL[, session S]': an AI agent wrote it")
    q.add_argument("--dry-run", action="store_true")
    q.set_defaults(fn=cmd_comment)

    args = p.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
